// Generated by gencpp from file action_tut/ExampleFeedback.msg
// DO NOT EDIT!


#ifndef ACTION_TUT_MESSAGE_EXAMPLEFEEDBACK_H
#define ACTION_TUT_MESSAGE_EXAMPLEFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace action_tut
{
template <class ContainerAllocator>
struct ExampleFeedback_
{
  typedef ExampleFeedback_<ContainerAllocator> Type;

  ExampleFeedback_()
    : sequence()  {
    }
  ExampleFeedback_(const ContainerAllocator& _alloc)
    : sequence(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _sequence_type;
  _sequence_type sequence;





  typedef boost::shared_ptr< ::action_tut::ExampleFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::action_tut::ExampleFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct ExampleFeedback_

typedef ::action_tut::ExampleFeedback_<std::allocator<void> > ExampleFeedback;

typedef boost::shared_ptr< ::action_tut::ExampleFeedback > ExampleFeedbackPtr;
typedef boost::shared_ptr< ::action_tut::ExampleFeedback const> ExampleFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::action_tut::ExampleFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::action_tut::ExampleFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace action_tut

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'action_tut': ['/home/ubuntu/workspace/melodic_gen/devel/share/action_tut/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::action_tut::ExampleFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::action_tut::ExampleFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::action_tut::ExampleFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::action_tut::ExampleFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::action_tut::ExampleFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::action_tut::ExampleFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::action_tut::ExampleFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b81e37d2a31925a0e8ae261a8699cb79";
  }

  static const char* value(const ::action_tut::ExampleFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb81e37d2a31925a0ULL;
  static const uint64_t static_value2 = 0xe8ae261a8699cb79ULL;
};

template<class ContainerAllocator>
struct DataType< ::action_tut::ExampleFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "action_tut/ExampleFeedback";
  }

  static const char* value(const ::action_tut::ExampleFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::action_tut::ExampleFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback\n"
"int32[] sequence\n"
"\n"
;
  }

  static const char* value(const ::action_tut::ExampleFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::action_tut::ExampleFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sequence);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ExampleFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::action_tut::ExampleFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::action_tut::ExampleFeedback_<ContainerAllocator>& v)
  {
    s << indent << "sequence[]" << std::endl;
    for (size_t i = 0; i < v.sequence.size(); ++i)
    {
      s << indent << "  sequence[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.sequence[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACTION_TUT_MESSAGE_EXAMPLEFEEDBACK_H
